version: 1.0.{build}
image: Ubuntu
environment:
  nodejs_version: "20"
install:
  - ps: Install-Product node `20` 
  - npm install -g yarn           
branches:
  only:
    - main
before_build:
  - yarn install
build_script:
  - yarn build
artifacts:
  - path: /dist
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist